BEGIN TRANSACTION;

INSERT INTO users (username,password_hash,role) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN');

--INSERT INTO timezones (name,abbreviation,utc_offset) VALUES ('Australian Eastern Standard Time', 'AEST', 10.0);
--INSERT INTO timezones (name,abbreviation,utc_offset) VALUES ('Australian Central Standard Time', 'ACST', 9.5);
--INSERT INTO timezones (name,abbreviation,utc_offset) VALUES ('Australian Western Standard Time', 'AWST', 8.0);
--INSERT INTO timezones (name,abbreviation,utc_offset) VALUES ('Eastern Standard Time', 'EST', -5.0);
--INSERT INTO timezones (name,abbreviation,utc_offset) VALUES ('Mountain Standard Time', 'MST', -6.0);
--INSERT INTO timezones (name,abbreviation,utc_offset) VALUES ('Central Standard Time', 'CST', -7.0);
--INSERT INTO timezones (name,abbreviation,utc_offset) VALUES ('Pacific Standard Time', 'PST', -8.0);
--
--INSERT INTO venues (stadium,city,state,timezone_id) VALUES ('Melbourne Cricket Ground','Melbourne','Victoria', (SELECT id FROM timezones WHERE abbreviation = 'AEST'));
--INSERT INTO venues (stadium,city,state,timezone_id) VALUES ('Optus Stadium','Perth','Western Australia', (SELECT id FROM timezones WHERE abbreviation = 'AWST'));
--INSERT INTO venues (stadium,city,state,timezone_id) VALUES ('Adelaide Oval','Adelaide','South Australia', (SELECT id FROM timezones WHERE abbreviation = 'ACST'));
--INSERT INTO venues (stadium,city,state,timezone_id) VALUES ('Marvel Stadium','Melbourne','Victoria',(SELECT id FROM timezones WHERE abbreviation = 'AEST'));
--INSERT INTO venues (stadium,city,state,timezone_id) VALUES ('Sydney Cricket Ground','Sydney','New South Wales', (SELECT id FROM timezones WHERE abbreviation = 'AEST'));
--INSERT INTO venues (stadium,city,state,timezone_id) VALUES ('The Gabba','Brisbane','Queensland', (SELECT id FROM timezones WHERE abbreviation = 'AEST'));
--INSERT INTO venues (stadium,city,state,timezone_id) VALUES ('GMHBA Stadium','Geelong','Victoria', (SELECT id FROM timezones WHERE abbreviation = 'AEST'));
--INSERT INTO venues (stadium,city,state,timezone_id) VALUES ('Heritage Bank Stadium','Gold Coast','Queensland', (SELECT id FROM timezones WHERE abbreviation = 'AEST'));
--INSERT INTO venues (stadium,city,state,timezone_id) VALUES ('Giants Stadium','Sydney','New South Wales', (SELECT id FROM timezones WHERE abbreviation = 'AEST'));
--INSERT INTO venues (stadium,city,state,timezone_id) VALUES ('University of Tasmania Stadium','Launceston','Tasmania', (SELECT id FROM timezones WHERE abbreviation = 'AEST'));
--INSERT INTO venues (stadium,city,state,timezone_id) VALUES ('Blundstone Arena','Hobart','Tasmania', (SELECT id FROM timezones WHERE abbreviation = 'AEST'));
--INSERT INTO venues (stadium,city,state,timezone_id) VALUES ('UNSW Canberra Oval','Canberra','ACT', (SELECT id FROM timezones WHERE abbreviation = 'AEST'));
--INSERT INTO venues (stadium,city,state,timezone_id) VALUES ('TIO Stadium','Darwin','Northern Territory', (SELECT id FROM timezones WHERE abbreviation = 'ACST'));
--INSERT INTO venues (stadium,city,state,timezone_id) VALUES ('Mars Stadium','Ballarat','Victoria', (SELECT id FROM timezones WHERE abbreviation = 'AEST'));
--INSERT INTO venues (stadium,city,state,timezone_id) VALUES ('TIO Traeger Park','Alice Springs','Northern Territory', (SELECT id FROM timezones WHERE abbreviation = 'ACST'));
--INSERT INTO venues (stadium,city,state,timezone_id) VALUES ('Norwood Oval', 'Adelaide', 'South Australia', (SELECT id FROM timezones WHERE abbreviation = 'ACST'));
--INSERT INTO venues (stadium,city,state,timezone_id) VALUES ('Adelaide Hills', 'Mt Barker', 'South Adelaide', (SELECT id FROM timezones WHERE abbreviation = 'ACST'));
--INSERT INTO venues (stadium,city,state,timezone_id) VALUES ('Manuka Oval', 'Canberra', 'ACT', (SELECT id FROM timezones WHERE abbreviation = 'AEST'));

INSERT INTO matches (team1, team2, round, start_time) VALUES ('Sydney Swans', 'Melbourne', 0, '2024-03-07 8:30:00');
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Brisbane Lions', 'Carlton', 0, '2024-03-08 8:40:00');
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Gold Coast Suns', 'Richmond', 0, '2024-03-09 5:20:00');
INSERT INTO matches (team1, team2, round, start_time) VALUES ('GWS Giants', 'Collingwood', 0, '2024-03-09 8:30:00');
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Carlton', 'Richmond', 1, '2024-03-14 8:30:00');
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Collingwood', 'Sydney Swans', 1, '2024-03-15 8:40:00');
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Essendon', 'Hawthorn', 1, '2024-03-16 2:45:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('GWS Giants', 'North Melbourne', 1, '2024-03-16 5:35:00');
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Geelong Cats', 'St Kilda', 1, '2024-03-16 8:30:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Gold Coast Suns', 'Adelaide Crows', 1, '2024-03-16 9:10:00');
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Melbourne', 'Western Bulldogs', 1, '2024-03-17 2:00:00');
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Port Adelaide', 'West Coast Eagles', 1, '2024-03-17 5:00:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Fremantle', 'Brisbane Lions', 1, '2024-03-17 7:50:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('St Kilda', 'Collingwood', 2, '2024-03-21 8:30:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Adelaide Crows', 'Geelong Cats', 2, '2024-03-22 8:40:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('North Melbourne', 'Fremantle', 2, '2024-03-23 2:45:00');
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Hawthorn', 'Melbourne', 2, '2024-03-23 5:35:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Sydney', 'Essendon', 2, '2024-03-23 8:30:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Western Bulldogs', 'Gold Coast Suns', 2, '2024-03-24 2:00:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Richmond', 'Port Adelaide', 2, '2024-03-24 5:00:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('West Coast Eagles', 'GWS Giants', 2, '2024-03-24 7:50:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Brisbane Lions', 'Collingwood', 3, '2024-03-28 8:30:00'
INSERT INTO matches (team1, team2, round, start_time) VALUES ('North Melbourne', 'Carlton', 3, '2024-03-29 5:20:00');
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Fremantle', 'Adelaide Crows', 3, '2024-03-29 8:20:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Essendon', 'St Kilda', 3, '2024-03-30 5:20:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Port Adelaide', 'Melbourne', 3, '2024-03-30 8:30:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Western Bulldogs', 'West Coast Eagles', 3, '2024-03-31 2:00:00');
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Richmond', 'Sydney Swans', 3, '2024-03-31 5:00:00');
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Hawthorn', 'Geelong Cats', 3, '2024-04-01 4:20:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Adelaide Crows', 'Melbourne', 4, '2024-04-04 8:40:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Brisbane Lions', 'North Melbourne', 4, '2024-04-05 6:10:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Port Adelaide', 'Essendon', 4, '2024-04-05 9:10:00');
INSERT INTO matches (team1, team2, round, start_time) VALUES ('West Coast Eagles', 'Sydney Swans', 4, '2024-04-06 2:30:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Fremantle', 'Carlton', 4, '2024-04-06 5:20:00');
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Western Bulldogs', 'Geelong Cats', 4, '2024-04-06 9:10:00');
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Gold Coast Suns', 'GWS Giants', 4, '2024-04-07 2:30:00');
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Richmond', 'St Kilda', 4, '2024-04-07 5:20:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Collingwood', 'Hawthorn', 4, '2024-04-07 7:10:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Melbourne', 'Brisbane Lions', 5, '2024-04-11 9:30:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Western Bulldogs', 'Essendon', 5, '2024-04-12 9:40:00');
INSERT INTO matches (team1, team2, round, start_time) VALUES ('GWS Giants', 'St Kilda', 5, '2024-04-13 3:45:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Carlton', 'Adelaide Crows', 5, '2024-04-13 6:35:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Gold Coast Suns', 'Hawthorn', 5, '2024-04-13 9:30:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Port Adelaide', 'Fremantle', 5, '2024-04-13 9:30:00');
INSERT INTO matches (team1, team2, round, start_time) VALUES ('Geelong Cats', 'North Melbourne', 5, '2024-04-14 3:00:00'); 
INSERT INTO matches (team1, team2, round, start_time) VALUES ('West Coast Eagles', 'Richmond', 5, '2024-04-14 6:00:00');


COMMIT TRANSACTION;
